### ISSUE TITLE
Error on player movement.

### ISSUE THREAD

**Issue by Dhs92** [Sablednah/LegendQuest#2]
<code>[17:02:03 ERROR]: Could not pass event PlayerMoveEvent to LegendQuest v1.8.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:265) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-dbe012b-63e28b1]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.skills.Skill.getPC(Skill.java:136) ~[?:?]
        at me.sablednah.legendquest.skills.Skill.validSkillUser(Skill.java:149) ~[?:?]
        at me.sablednah.legendquest.skills.WaterWalk.doMove(WaterWalk.java:69) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-dbe012b-63e28b1]
</code>

**Comment by Dhs92** [comment]
FIXED

**Comment by Sablednah** [comment]
Glad to hear its fixed.  What was it?  It looks like its failed to load a character from the database?
