### ISSUE TITLE
Issue on player interact?

### ISSUE THREAD

**Issue by StargateMC** [Sablednah/LegendQuest#3]
```
Could not pass event PlayerInteractEvent to LegendQuest v1.9.7
org.bukkit.event.EventException
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.30]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.30]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.30]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.30]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:238) [ForgeEventFactory.class:1.7.10-1614.30]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick2(TileActivator.java:434) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:401) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:217) [TileActivator.class:?]
        at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:176) [TileActivator.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2531) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:967) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2233) ~[?:?]
        at me.sablednah.legendquest.playercharacters.PC.getLoadout(PC.java:2227) ~[?:?]
        at me.sablednah.legendquest.listeners.SkillLinkEvents.onInteract(SkillLinkEvents.java:61) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 17 more

```

**Comment by StargateMC** [comment]
Closed this is not a LQ issue.
